name: CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8 # Use latest pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x # Match engines requirement
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run test
      - run: pnpm run build 